### ISSUE TITLE
Math question solver in JobAutoReload stop working?

### ISSUE THREAD

**Issue by DrogonRocks** [sweeneyapps/JobAutoReload#1]
Hi sweeny i really love all the work you do to make our lifes easier while doing hits, i use both of your scripts for rainforest and 1 week ago i started using JobAutoReload since i read that it could do the math question and save us time, it was working good until today, everytime i have a math question i press ctrl+shift+A and now it doesn't show the box with the answer, i tried re-installing the extension and even re-installing google chrome but it still without working, the sound stills working but the math question solver don't, any ideas on what is causing this? don't know if RF changed something and now it's broken or if it is something wrong on my side

**Comment by DrogonRocks** [comment]
Nevermind, i managed to fix it by changing the Keyboard shortcuts to activate it :)

**Comment by sweeneyapps** [comment]
ahh, I was going to look at it.     but that's great..    yeah keyboard shortcuts setting is out of my reach.  It's up to the users to active it or not.
